
# Screen Settings
# SCREEN_WIDTH = 700
# SCREEN_HEIGHT = 1000
SCREEN_HEIGHT = 1065
SCREEN_WIDTH = 1920
SCREEN_TITLE = "The Cistern"
PLAYING_FIELD_WIDTH = SCREEN_WIDTH - 50
PLAYING_FIELD_HEIGHT = SCREEN_HEIGHT - 50

# Speeds
CAMERA_SPEED = 0.9
PLAYER_MOVEMENT_SPEED = 1.2
PLAYER_RUN_SPEED_MODIFIER = 1.8
SLASH_SPEED_MODIFIER = 0.15
SLASH_CHARGE_SPEED_MODIFIER = 0.8
SLASH_PROJECTILE_SPEED = 1.9
MONSTER_MOVEMENT_SPEED = 1.45

# Timing Settings
SWORDSLASH_FPS = 1/70
SLASH_CHARGE_TIME = 0.05

# Sizes
SPOTLIGHT_SIZE = 500
MONSTER_VISION_RANGE = 400
SPRITE_SCALING = 0.25
PLAYER_SCALING = 0.4
MONSTER_SCALING = 0.5
SWORD_SLASH_SCALING = 0.35
HEART_SCALING = 0.1

# Alpha
GHOST_ALPHA = 210

# Health settings, amount of life per heart
HEART_HEALTH = 10
PLAYER_STARTING_HEALTH = 40

# Volume settings
MUSIC_VOLUME = 0.3
SWOOSH_VOLUME = 0.2
