# Screen Settings
SCREEN_WIDTH = 700
SCREEN_HEIGHT = 1000
SCREEN_TITLE = "The Cistercian Cistern"
PLAYING_FIELD_WIDTH = SCREEN_WIDTH - 50
PLAYING_FIELD_HEIGHT = SCREEN_HEIGHT - 50
SPOTLIGHT_SIZE = 350

# Scaling Settings
SPRITE_SCALING = 0.25
PLAYER_SCALING = 0.4
MONSTER_SCALING = 0.5

# How fast the camera pans to the player. 1.0 is instant.
CAMERA_SPEED = 0.9

# Movement settings
PLAYER_MOVEMENT_SPEED = 1.5
RUN_SPEED_MODIFIER = 2
SLASH_SPEED_MODIFIER = 0.15
SLASH_CHARGE_SPEED_MODIFIER = 0.8

# Time settings
SLASH_CHARGE_TIME = 0.04